# ruff: noqa: E501
# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, Field, RootModel


class ConfigStateResponse(BaseModel):
    sha256: Annotated[str, Field(title='Sha256')]
    yaml: Annotated[str, Field(title='Yaml')]


class CopyTemplateRequest(BaseModel):
    name: Annotated[str | None, Field(title='Name')] = None
    source_ref: Annotated[str, Field(title='Source Ref')]


class Protocol(Enum):
    openai_compatible = 'openai_compatible'
    anthropic_compatible = 'anthropic_compatible'
    image_generation = 'image_generation'


class CreateEndpointRequest(BaseModel):
    adapter: Annotated[str | None, Field(title='Adapter')] = None
    api_key: Annotated[str, Field(title='Api Key')]
    base_url: Annotated[str, Field(title='Base Url')]
    model: Annotated[str, Field(title='Model')]
    name: Annotated[str, Field(title='Name')]
    protocol: Annotated[Protocol, Field(title='Protocol')]


class DeleteKitImageResponse(BaseModel):
    deleted: Annotated[bool, Field(title='Deleted')]
    file_deleted: Annotated[bool, Field(title='File Deleted')]
    image_id: Annotated[str, Field(title='Image Id')]
    kit_id: Annotated[int, Field(title='Kit Id')]


class Id(Enum):
    M1 = 'M1'
    M2 = 'M2'
    M3 = 'M3'
    M4 = 'M4'
    M5 = 'M5'
    M6 = 'M6'
    M7 = 'M7'
    M8 = 'M8'
    M9 = 'M9'


class EditAccepted(BaseModel):
    job_id: Annotated[str, Field(title='Job Id')]


class KitId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Optional kit id for local edit context; safe-character allowlist keeps sidecar references portable.',
            pattern='^[A-Za-z0-9_-]{1,64}$',
            title='Kit Id',
        ),
    ]


class EditRequest(BaseModel):
    kit_id: Annotated[
        KitId | None,
        Field(
            description='Optional kit id for local edit context; safe-character allowlist keeps sidecar references portable.',
            title='Kit Id',
        ),
    ] = None
    mask_box: Annotated[dict[str, int], Field(description='x,y,w,h', title='Mask Box')]
    new_text: Annotated[str, Field(title='New Text')]


class EndpointSecretResponse(BaseModel):
    api_key: Annotated[str, Field(title='Api Key')]


class EndpointStanza(BaseModel):
    adapter: Annotated[str | None, Field(title='Adapter')] = None
    api_key_env: Annotated[str, Field(title='Api Key Env')]
    base_url: Annotated[str, Field(title='Base Url')]
    model: Annotated[str, Field(title='Model')]
    protocol: Annotated[str, Field(title='Protocol')]


class Description(RootModel[str]):
    root: Annotated[str, Field(max_length=2000, title='Description')]


class ExtractRequest(BaseModel):
    description: Annotated[Description | None, Field(title='Description')] = None
    image_url: Annotated[str, Field(max_length=12000000, title='Image Url')]


class FieldInference(BaseModel):
    confidence: Annotated[float, Field(ge=0.0, le=1.0, title='Confidence')]
    reasoning: Annotated[str, Field(title='Reasoning')]
    value: Annotated[Any, Field(title='Value')]


class Locale(Enum):
    zh = 'zh'
    en = 'en'


class GenerateResponse(BaseModel):
    abort_reason: Annotated[str | None, Field(title='Abort Reason')] = None
    color_lock_summary: Annotated[dict[str, int], Field(title='Color Lock Summary')]
    compliance_path: Annotated[str, Field(title='Compliance Path')]
    cost_path: Annotated[str, Field(title='Cost Path')]
    db_kit_id: Annotated[int, Field(title='Db Kit Id')]
    kit_id: Annotated[str, Field(title='Kit Id')]
    needs_review: Annotated[bool, Field(title='Needs Review')]
    png_paths: Annotated[list[str], Field(title='Png Paths')]


class Id2(Enum):
    H1 = 'H1'
    H2 = 'H2'
    H3 = 'H3'
    H4 = 'H4'
    H5 = 'H5'


class KitListItem(BaseModel):
    category: Annotated[str | None, Field(title='Category')] = None
    id: Annotated[int, Field(title='Id')]
    locale: Annotated[str | None, Field(title='Locale')]
    name: Annotated[str, Field(title='Name')]
    name_en: Annotated[str | None, Field(title='Name En')]
    score: Annotated[int | None, Field(title='Score')]
    sku: Annotated[str, Field(title='Sku')]
    status: Annotated[str, Field(title='Status')]
    thumbs: Annotated[list[str | None], Field(title='Thumbs')]
    updated_at: Annotated[str | None, Field(title='Updated At')] = None


class KitListResponse(BaseModel):
    items: Annotated[list[KitListItem], Field(title='Items')]
    total: Annotated[int, Field(title='Total')]


class KitMetaResponse(BaseModel):
    compliance: Annotated[dict[str, Any] | None, Field(title='Compliance')] = None
    cost: Annotated[dict[str, Any] | None, Field(title='Cost')] = None
    db_kit_id: Annotated[int, Field(title='Db Kit Id')]
    kit_id: Annotated[str | None, Field(title='Kit Id')] = None
    retrieved_bestseller_ids: Annotated[
        list[int], Field(title='Retrieved Bestseller Ids')
    ]
    spec: Annotated[dict[str, Any] | None, Field(title='Spec')] = None
    spec_markdown: Annotated[str | None, Field(title='Spec Markdown')] = None


class OnboardingNeededResponse(BaseModel):
    needs_onboarding: Annotated[bool, Field(title='Needs Onboarding')]


class PreviewRequest(BaseModel):
    brand_color_hex: Annotated[
        str | None, Field(pattern='^#[0-9A-Fa-f]{6}$', title='Brand Color Hex')
    ] = '#C4513A'
    copy_: Annotated[str | None, Field(alias='copy', title='Copy')] = '新品上市'
    design_note: Annotated[str | None, Field(title='Design Note')] = (
        'keep product centered with premium spacing'
    )
    locale: Annotated[Locale, Field(title='Locale')]
    sample_brand: Annotated[str | None, Field(title='Sample Brand')] = '示例品牌'
    sample_category: Annotated[str | None, Field(title='Sample Category')] = '服饰'
    sample_name: Annotated[str | None, Field(title='Sample Name')] = '示例商品'
    style_prompt: Annotated[str | None, Field(title='Style Prompt')] = (
        'warm minimalist studio, soft daylight'
    )
    template_ref: Annotated[str, Field(title='Template Ref')]
    visual: Annotated[str | None, Field(title='Visual')] = (
        'single product hero image, clean ecommerce composition'
    )


class PreviewResponse(BaseModel):
    cost_usd: Annotated[float, Field(title='Cost Usd')]
    png_path: Annotated[str | None, Field(title='Png Path')]
    prompt: Annotated[str, Field(title='Prompt')]


class ProbeCandidateRequest(BaseModel):
    adapter: Annotated[str | None, Field(title='Adapter')] = None
    api_key: Annotated[str | None, Field(title='Api Key')] = None
    api_key_env: Annotated[str | None, Field(title='Api Key Env')] = None
    base_url: Annotated[str, Field(title='Base Url')]
    protocol: Annotated[Protocol, Field(title='Protocol')]


class ProbeCandidateResponse(BaseModel):
    error: Annotated[str | None, Field(title='Error')] = None
    latency_ms: Annotated[int, Field(title='Latency Ms')]
    models: Annotated[list[str], Field(title='Models')]
    ok: Annotated[bool, Field(title='Ok')]


class Status(Enum):
    ok = 'ok'
    warn = 'warn'
    error = 'error'


class ProviderHealthRow(BaseModel):
    base_url: Annotated[str | None, Field(title='Base Url')]
    endpoint_id: Annotated[str, Field(title='Endpoint Id')]
    last_check: Annotated[str | None, Field(title='Last Check')]
    latency_ms: Annotated[int | None, Field(title='Latency Ms')]
    role: Annotated[str, Field(title='Role')]
    status: Annotated[Status | None, Field(title='Status')]
    unbound: Annotated[list[str] | None, Field(title='Unbound')] = None


class ProviderProbeRow(BaseModel):
    error: Annotated[str | None, Field(title='Error')] = None
    latency_ms: Annotated[int, Field(title='Latency Ms')]
    models: Annotated[list[str], Field(title='Models')]
    ok: Annotated[bool, Field(title='Ok')]
    role: Annotated[str, Field(title='Role')]


class ProvidersSummaryResponse(BaseModel):
    brand_color: Annotated[str | None, Field(title='Brand Color')]
    default_locale: Annotated[str | None, Field(title='Default Locale')]
    endpoints_count: Annotated[int, Field(title='Endpoints Count')]
    export_preset: Annotated[str | None, Field(title='Export Preset')]
    monthly_cap_usd: Annotated[float | None, Field(title='Monthly Cap Usd')]


class Stage(Enum):
    done = 'done'
    active = 'active'
    queued = 'queued'


class QueueJob(BaseModel):
    current_stage: Annotated[str, Field(title='Current Stage')]
    eta_ms: Annotated[int, Field(title='Eta Ms')]
    kit_id: Annotated[str, Field(title='Kit Id')]
    locale: Annotated[str | None, Field(title='Locale')]
    name: Annotated[str | None, Field(title='Name')]
    sku: Annotated[str | None, Field(title='Sku')]
    stages: Annotated[list[Stage], Field(title='Stages')]


class SaveEndpointsRequest(BaseModel):
    expected_sha256: Annotated[str, Field(title='Expected Sha256')]
    new_yaml: Annotated[str, Field(title='New Yaml')]


class SaveEndpointsResponse(BaseModel):
    new_sha256: Annotated[str, Field(title='New Sha256')]
    registry_rebooted: Annotated[bool | None, Field(title='Registry Rebooted')] = True
    warning: Annotated[str | None, Field(title='Warning')] = None


class SlotId(Enum):
    H1 = 'H1'
    H2 = 'H2'
    H3 = 'H3'
    H4 = 'H4'
    H5 = 'H5'
    M1 = 'M1'
    M2 = 'M2'
    M3 = 'M3'
    M4 = 'M4'
    M5 = 'M5'
    M6 = 'M6'
    M7 = 'M7'
    M8 = 'M8'
    M9 = 'M9'


class SchemeSlot(BaseModel):
    slot_id: Annotated[SlotId, Field(title='Slot Id')]
    template_ref: Annotated[str, Field(title='Template Ref')]


class Source(Enum):
    built_in = 'built_in'
    custom = 'custom'


class SchemeSummary(BaseModel):
    description: Annotated[str | None, Field(title='Description')] = None
    editable: Annotated[bool | None, Field(title='Editable')] = True
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    id: Annotated[str, Field(title='Id')]
    locale: Annotated[Locale, Field(title='Locale')]
    name: Annotated[str, Field(title='Name')]
    slots: Annotated[list[SchemeSlot], Field(title='Slots')]
    source: Annotated[Source | None, Field(title='Source')] = Source.custom


class Priority(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class SellingPointIn(BaseModel):
    evidence: Annotated[str, Field(title='Evidence')]
    priority: Annotated[Priority, Field(title='Priority')]
    title: Annotated[str, Field(title='Title')]


class SettingsResponse(BaseModel):
    brand_color: Annotated[str | None, Field(title='Brand Color')]
    default_locale: Annotated[str | None, Field(title='Default Locale')]
    export_preset: Annotated[str | None, Field(title='Export Preset')]
    monthly_cap_usd: Annotated[float | None, Field(title='Monthly Cap Usd')]


class DefaultLocale(Enum):
    zh = 'zh'
    en = 'en'


class MonthlyCapUsd(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title='Monthly Cap Usd')]


class SettingsUpdate(BaseModel):
    brand_color: Annotated[str | None, Field(title='Brand Color')] = None
    default_locale: Annotated[DefaultLocale | None, Field(title='Default Locale')] = (
        None
    )
    export_preset: Annotated[str | None, Field(title='Export Preset')] = None
    monthly_cap_usd: Annotated[MonthlyCapUsd | None, Field(title='Monthly Cap Usd')] = (
        None
    )


class ProductType(Enum):
    blue_hat = 'blue_hat'
    sports = 'sports'
    general_food = 'general_food'
    other = 'other'


class SkuMetaIn(BaseModel):
    brand: Annotated[str, Field(title='Brand')]
    category: Annotated[str, Field(title='Category')]
    name: Annotated[str | None, Field(title='Name')] = None
    price: Annotated[float, Field(title='Price')]
    product_type: Annotated[ProductType, Field(title='Product Type')]
    sku: Annotated[str | None, Field(title='Sku')] = None


class Sparks(BaseModel):
    compliance: Annotated[list[float], Field(title='Compliance')]
    cost: Annotated[list[float], Field(title='Cost')]
    kits: Annotated[list[int], Field(title='Kits')]


class SpecRequest(BaseModel):
    locale: Annotated[Locale, Field(title='Locale')]
    selling_points: Annotated[
        list[SellingPointIn], Field(min_length=1, title='Selling Points')
    ]
    sku_meta: SkuMetaIn


class StoreSecretRequest(BaseModel):
    api_key: Annotated[str, Field(title='Api Key')]
    name: Annotated[str, Field(title='Name')]
    role: Annotated[str, Field(title='Role')]


class StoreSecretResponse(BaseModel):
    api_key_env: Annotated[str, Field(title='Api Key Env')]


class Category(Enum):
    hero = 'hero'
    detail_m3 = 'detail_m3'
    lifestyle = 'lifestyle'
    short_video = 'short_video'
    amazon_hero = 'amazon_hero'


class TemplatePayload(BaseModel):
    category: Annotated[Category | None, Field(title='Category')] = Category.lifestyle
    category_tips: Annotated[dict[str, str] | None, Field(title='Category Tips')] = None
    defaults: Annotated[dict[str, str] | None, Field(title='Defaults')] = None
    description: Annotated[str | None, Field(title='Description')] = None
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    examples: Annotated[list[str] | None, Field(title='Examples')] = None
    locale: Annotated[Locale, Field(title='Locale')]
    name: Annotated[str, Field(min_length=1, title='Name')]
    prompt_template: Annotated[dict[str, str], Field(title='Prompt Template')]
    supports_image_reference: Annotated[
        bool | None, Field(title='Supports Image Reference')
    ] = False
    tags: Annotated[list[str] | None, Field(title='Tags')] = None
    variants: Annotated[dict[str, Any] | None, Field(title='Variants')] = None


class TemplateSummary(BaseModel):
    category: Annotated[Category, Field(title='Category')]
    copyable: Annotated[bool | None, Field(title='Copyable')] = True
    defaults: Annotated[dict[str, str] | None, Field(title='Defaults')] = None
    description: Annotated[str | None, Field(title='Description')]
    editable: Annotated[bool | None, Field(title='Editable')] = False
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    examples: Annotated[list[str] | None, Field(title='Examples')] = None
    id: Annotated[str, Field(title='Id')]
    locale: Annotated[Locale, Field(title='Locale')]
    name: Annotated[str, Field(title='Name')]
    name_en: Annotated[str | None, Field(title='Name En')] = None
    prompt_template: Annotated[
        dict[str, str] | None, Field(title='Prompt Template')
    ] = None
    source: Annotated[Source | None, Field(title='Source')] = Source.built_in
    tags: Annotated[list[str], Field(title='Tags')]
    thumbnail_url: Annotated[str | None, Field(title='Thumbnail Url')]


class TemplateUpdate(BaseModel):
    category: Annotated[Category | None, Field(title='Category')] = None
    category_tips: Annotated[dict[str, str] | None, Field(title='Category Tips')] = None
    defaults: Annotated[dict[str, str] | None, Field(title='Defaults')] = None
    description: Annotated[str | None, Field(title='Description')] = None
    enabled: Annotated[bool | None, Field(title='Enabled')] = None
    examples: Annotated[list[str] | None, Field(title='Examples')] = None
    name: Annotated[str | None, Field(title='Name')] = None
    prompt_template: Annotated[
        dict[str, str] | None, Field(title='Prompt Template')
    ] = None
    supports_image_reference: Annotated[
        bool | None, Field(title='Supports Image Reference')
    ] = None
    tags: Annotated[list[str] | None, Field(title='Tags')] = None
    variants: Annotated[dict[str, Any] | None, Field(title='Variants')] = None


class TextBoxOut(BaseModel):
    confidence: Annotated[float, Field(title='Confidence')]
    h: Annotated[int, Field(title='H')]
    text: Annotated[str, Field(title='Text')]
    w: Annotated[int, Field(title='W')]
    x: Annotated[int, Field(title='X')]
    y: Annotated[int, Field(title='Y')]


class ThreePieceIn(BaseModel):
    copy_: Annotated[str, Field(alias='copy', title='Copy')]
    design_note: Annotated[str, Field(title='Design Note')]
    visual: Annotated[str, Field(title='Visual')]


class ThreePieceOut(BaseModel):
    copy_: Annotated[str, Field(alias='copy', title='Copy')]
    design_note: Annotated[str, Field(title='Design Note')]
    visual: Annotated[str, Field(title='Visual')]


class UpdateEndpointRequest(BaseModel):
    adapter: Annotated[str | None, Field(title='Adapter')] = None
    api_key: Annotated[str | None, Field(title='Api Key')] = None
    base_url: Annotated[str, Field(title='Base Url')]
    model: Annotated[str, Field(title='Model')]
    name: Annotated[str, Field(title='Name')]
    protocol: Annotated[Protocol, Field(title='Protocol')]


class ValidationError(BaseModel):
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None
    input: Annotated[Any | None, Field(title='Input')] = None
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class Severity(Enum):
    hard_block = 'hard_block'
    warning = 'warning'
    advisory = 'advisory'


class ViolationOut(BaseModel):
    location: Annotated[str, Field(title='Location')]
    matched_text: Annotated[str, Field(title='Matched Text')]
    rule_id: Annotated[str, Field(title='Rule Id')]
    severity: Annotated[Severity, Field(title='Severity')]
    suggestion: Annotated[str | None, Field(title='Suggestion')] = None


class WeeklyMetricsResponse(BaseModel):
    api_spend_usd_mtd: Annotated[float, Field(title='Api Spend Usd Mtd')]
    avg_compliance: Annotated[float | None, Field(title='Avg Compliance')]
    avg_manual_edit_min: Annotated[float | None, Field(title='Avg Manual Edit Min')]
    kits_this_week: Annotated[int, Field(title='Kits This Week')]
    sparks: Sparks


class ComplianceOut(BaseModel):
    advisory: Annotated[bool, Field(title='Advisory')]
    locale: Annotated[str, Field(title='Locale')]
    score: Annotated[int, Field(title='Score')]
    violations: Annotated[list[ViolationOut], Field(title='Violations')]


class DetailSectionIn(BaseModel):
    id: Annotated[Id, Field(title='Id')]
    three_piece: ThreePieceIn


class DetailSectionOut(BaseModel):
    id: Annotated[Id, Field(title='Id')]
    three_piece: ThreePieceOut


class ExtractResponse(BaseModel):
    brand: FieldInference
    brand_color_hex: FieldInference
    category: FieldInference
    name: FieldInference | None
    price: FieldInference | None
    product_type: FieldInference
    selling_points: Annotated[list[FieldInference], Field(title='Selling Points')]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class HeroSectionIn(BaseModel):
    id: Annotated[Id2, Field(title='Id')]
    three_piece: ThreePieceIn


class HeroSectionOut(BaseModel):
    id: Annotated[Id2, Field(title='Id')]
    three_piece: ThreePieceOut


class OcrResponse(BaseModel):
    boxes: Annotated[list[TextBoxOut], Field(title='Boxes')]
    engine: Annotated[str, Field(title='Engine')]
    version: Annotated[str, Field(title='Version')]


class ProviderProbeResponse(BaseModel):
    rows: Annotated[list[ProviderProbeRow], Field(title='Rows')]


class SchemePayload(BaseModel):
    description: Annotated[str | None, Field(title='Description')] = None
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    locale: Annotated[Locale, Field(title='Locale')]
    name: Annotated[str, Field(min_length=1, title='Name')]
    slots: Annotated[
        list[SchemeSlot], Field(max_length=14, min_length=14, title='Slots')
    ]


class SpecIn(BaseModel):
    detail_sections: Annotated[
        list[DetailSectionIn],
        Field(max_length=9, min_length=9, title='Detail Sections'),
    ]
    hero_sections: Annotated[
        list[HeroSectionIn], Field(max_length=5, min_length=5, title='Hero Sections')
    ]
    locale: Annotated[Locale, Field(title='Locale')]
    selling_points: Annotated[
        list[SellingPointIn], Field(min_length=1, title='Selling Points')
    ]
    sku_meta: SkuMetaIn


class SpecOut(BaseModel):
    detail_sections: Annotated[
        list[DetailSectionOut],
        Field(max_length=9, min_length=9, title='Detail Sections'),
    ]
    hero_sections: Annotated[
        list[HeroSectionOut], Field(max_length=5, min_length=5, title='Hero Sections')
    ]
    locale: Annotated[Locale, Field(title='Locale')]
    selling_points: Annotated[list[SellingPointIn], Field(title='Selling Points')]
    sku_meta: SkuMetaIn


class SpecResponse(BaseModel):
    compliance: ComplianceOut
    spec: SpecOut
    spec_markdown: Annotated[str, Field(title='Spec Markdown')]


class GenerateRequest(BaseModel):
    brand_color_hex: Annotated[
        str, Field(pattern='^#[0-9A-Fa-f]{6}$', title='Brand Color Hex')
    ]
    locale: Annotated[Locale, Field(title='Locale')]
    retrieved_bestseller_ids: Annotated[
        list[int] | None, Field(title='Retrieved Bestseller Ids')
    ] = None
    spec: SpecIn
    style_prompt: Annotated[str | None, Field(title='Style Prompt')] = None
    template_scheme_ref: Annotated[str | None, Field(title='Template Scheme Ref')] = (
        None
    )
    template_slot_overrides: Annotated[
        dict[str, str] | None, Field(title='Template Slot Overrides')
    ] = None
