/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/images/{image_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Edit */
        post: operations["start_edit_api_images__image_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/edit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Edit Events */
        get: operations["edit_events_api_images__image_id__edit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ocr Image */
        post: operations["ocr_image_api_images__image_id__ocr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Kits
         * @description Return the latest ``limit`` kits joined with their product catalog row.
         *
         *     ``thumbs`` is the concatenation of up-to-5 hero png_paths (slot 1..5) and
         *     up-to-9 detail png_paths (M1..M9) — 14 slots total, NULL-padded for any
         *     missing rows.  Callers render placeholder cells for NULL entries.
         *
         *     ``recent`` is currently advisory; the route always sorts by ``created_at
         *     DESC``.  The flag exists so the frontend can call ``/api/kits?recent=true``
         *     without a 404 from a path mismatch.
         */
        get: operations["list_kits_api_kits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kits/{kit_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kit Events
         * @description Stream per-image status events for *kit_id* as text/event-stream.
         *
         *     Returns 404 when the kit_id has never been published to the bus
         *     (callers can use this as a "kit not started" signal).  Each line
         *     conforms to the SSE wire format::
         *
         *         data: {"image_id": "H1", "status": "color_locked", "progress": 0,
         *                "brand_color_locked": true}
         */
        get: operations["get_kit_events_api_kits__kit_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kits/{kit_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Generate
         * @description Generate the 14-image kit for *kit_id*.
         */
        post: operations["post_generate_api_kits__kit_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kits/{kit_id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Spec
         * @description Generate the marketing spec for *kit_id* under the requested locale.
         */
        post: operations["create_spec_api_kits__kit_id__spec_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weekly Metrics
         * @description Aggregate live metrics — current-ISO-week kits + 12-week sparklines.
         */
        get: operations["get_weekly_metrics_api_metrics_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/needed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Onboarding Needed
         * @description Return whether onboarding is needed for this workspace.
         */
        get: operations["get_onboarding_needed_api_onboarding_needed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Endpoints
         * @description Save the new config YAML body.  ADR-010 v2 lock+checksum semantics.
         */
        post: operations["save_endpoints_api_providers_endpoints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provider Health
         * @description Per-role health snapshot derived from ``app.state.registry``.
         *
         *     Latency probes are not yet implemented (status/latency_ms stubbed to
         *     None).  When a known role has no binding, the row carries the role
         *     name in ``unbound`` so the frontend can render the warning chip.
         */
        get: operations["get_provider_health_api_providers_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provider Summary
         * @description Summary of the on-disk ``config.yaml``.
         */
        get: operations["get_provider_summary_api_providers_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Queue
         * @description Return the snapshot of active kits.  Empty list when idle.
         */
        get: operations["get_active_queue_api_queue_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrieval/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description POST /api/retrieval/search — embed query image + hybrid retrieve.
         */
        post: operations["search_api_retrieval_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Probe Postgres, Milvus, Redis, MinIO concurrently with a 2s timeout each.
         *     Returns overall status 'ok' if all four connected, else 'degraded'.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComplianceOut */
        ComplianceOut: {
            /** Advisory */
            advisory: boolean;
            /** Locale */
            locale: string;
            /** Score */
            score: number;
            /** Violations */
            violations: components["schemas"]["ViolationOut"][];
        };
        /** DetailSectionIn */
        DetailSectionIn: {
            /**
             * Id
             * @enum {string}
             */
            id: "M1" | "M2" | "M3" | "M4" | "M5" | "M6" | "M7" | "M8" | "M9";
            three_piece: components["schemas"]["ThreePieceIn"];
        };
        /** EditAccepted */
        EditAccepted: {
            /** Job Id */
            job_id: string;
        };
        /** EditRequest */
        EditRequest: {
            /**
             * Kit Id
             * @description Optional kit id for MinIO sidecar write; safe-character allowlist guards the object-store path.
             */
            kit_id?: string | null;
            /**
             * Mask Box
             * @description x,y,w,h
             */
            mask_box: {
                [key: string]: number;
            };
            /** New Text */
            new_text: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Brand Color Hex */
            brand_color_hex: string;
            /**
             * Locale
             * @enum {string}
             */
            locale: "zh" | "en";
            spec: components["schemas"]["SpecIn"];
            /** Style Prompt */
            style_prompt?: string | null;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Abort Reason */
            abort_reason?: string | null;
            /** Color Lock Summary */
            color_lock_summary: {
                [key: string]: number;
            };
            /** Compliance Path */
            compliance_path: string;
            /** Cost Path */
            cost_path: string;
            /** Kit Id */
            kit_id: string;
            /** Needs Review */
            needs_review: boolean;
            /** Png Paths */
            png_paths: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeroSectionIn */
        HeroSectionIn: {
            /**
             * Id
             * @enum {string}
             */
            id: "H1" | "H2" | "H3" | "H4" | "H5";
            three_piece: components["schemas"]["ThreePieceIn"];
        };
        /** KitListItem */
        KitListItem: {
            /** Id */
            id: number;
            /** Locale */
            locale: string | null;
            /** Name */
            name: string;
            /** Name En */
            name_en: string | null;
            /** Score */
            score: number | null;
            /** Sku */
            sku: string;
            /** Status */
            status: string;
            /** Thumbs */
            thumbs: (string | null)[];
        };
        /** KitListResponse */
        KitListResponse: {
            /** Items */
            items: components["schemas"]["KitListItem"][];
            /** Total */
            total: number;
        };
        /** OcrResponse */
        OcrResponse: {
            /** Boxes */
            boxes: components["schemas"]["TextBoxOut"][];
            /** Engine */
            engine: string;
            /** Version */
            version: string;
        };
        /** OnboardingNeededResponse */
        OnboardingNeededResponse: {
            /** Needs Onboarding */
            needs_onboarding: boolean;
        };
        /** ProviderHealthRow */
        ProviderHealthRow: {
            /** Endpoint Id */
            endpoint_id: string;
            /** Last Check */
            last_check: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Role */
            role: string;
            /** Status */
            status: ("ok" | "warn" | "error") | null;
            /** Unbound */
            unbound?: string[] | null;
        };
        /** ProvidersSummaryResponse */
        ProvidersSummaryResponse: {
            /** Brand Color */
            brand_color: string | null;
            /** Default Locale */
            default_locale: string | null;
            /** Endpoints Count */
            endpoints_count: number;
            /** Export Preset */
            export_preset: string | null;
            /** Monthly Cap Usd */
            monthly_cap_usd: number | null;
        };
        /** QueueJob */
        QueueJob: {
            /** Current Stage */
            current_stage: string;
            /** Eta Ms */
            eta_ms: number;
            /** Kit Id */
            kit_id: string;
            /** Locale */
            locale: string | null;
            /** Name */
            name: string | null;
            /** Sku */
            sku: string | null;
            /** Stages */
            stages: ("done" | "active" | "queued")[];
        };
        /** SaveEndpointsRequest */
        SaveEndpointsRequest: {
            /** Expected Sha256 */
            expected_sha256: string;
            /** New Yaml */
            new_yaml: string;
        };
        /** SaveEndpointsResponse */
        SaveEndpointsResponse: {
            /** New Sha256 */
            new_sha256: string;
        };
        /** SearchHitOut */
        SearchHitOut: {
            /** Image Url */
            image_url: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Score */
            score: number;
        };
        /** SearchRequest */
        SearchRequest: {
            /** @default {} */
            filters: components["schemas"]["_Filters"];
            /** Image */
            image: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Hits */
            hits: components["schemas"]["SearchHitOut"][];
        };
        /** SellingPointIn */
        SellingPointIn: {
            /** Evidence */
            evidence: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "high" | "medium" | "low";
            /** Title */
            title: string;
        };
        /** SkuMetaIn */
        SkuMetaIn: {
            /** Brand */
            brand: string;
            /** Category */
            category: string;
            /** Name */
            name: string;
            /** Price */
            price: number;
            /**
             * Product Type
             * @enum {string}
             */
            product_type: "blue_hat" | "sports" | "general_food" | "other";
            /** Sku */
            sku: string;
        };
        /** Sparks */
        Sparks: {
            /** Compliance */
            compliance: number[];
            /** Cost */
            cost: number[];
            /** Kits */
            kits: number[];
        };
        /** SpecIn */
        SpecIn: {
            /** Detail Sections */
            detail_sections: components["schemas"]["DetailSectionIn"][];
            /** Hero Sections */
            hero_sections: components["schemas"]["HeroSectionIn"][];
            /**
             * Locale
             * @enum {string}
             */
            locale: "zh" | "en";
            /** Selling Points */
            selling_points: components["schemas"]["SellingPointIn"][];
            sku_meta: components["schemas"]["SkuMetaIn"];
        };
        /** SpecRequest */
        SpecRequest: {
            /**
             * Locale
             * @enum {string}
             */
            locale: "zh" | "en";
            /** Selling Points */
            selling_points: components["schemas"]["SellingPointIn"][];
            sku_meta: components["schemas"]["SkuMetaIn"];
        };
        /** SpecResponse */
        SpecResponse: {
            compliance: components["schemas"]["ComplianceOut"];
            /** Spec Markdown */
            spec_markdown: string;
        };
        /** TextBoxOut */
        TextBoxOut: {
            /** Confidence */
            confidence: number;
            /** H */
            h: number;
            /** Text */
            text: string;
            /** W */
            w: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ThreePieceIn */
        ThreePieceIn: {
            /** Copy */
            copy: string;
            /** Design Note */
            design_note: string;
            /** Visual */
            visual: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ViolationOut */
        ViolationOut: {
            /** Location */
            location: string;
            /** Matched Text */
            matched_text: string;
            /** Rule Id */
            rule_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "hard_block" | "warning" | "advisory";
            /** Suggestion */
            suggestion?: string | null;
        };
        /** WeeklyMetricsResponse */
        WeeklyMetricsResponse: {
            /** Api Spend Usd Mtd */
            api_spend_usd_mtd: number;
            /** Avg Compliance */
            avg_compliance: number | null;
            /** Avg Manual Edit Min */
            avg_manual_edit_min: number | null;
            /** Kits This Week */
            kits_this_week: number;
            sparks: components["schemas"]["Sparks"];
        };
        /** _Filters */
        _Filters: {
            /** Category */
            category?: string | null;
            /** Fallback Locale */
            fallback_locale?: string | null;
            /** Locale */
            locale?: string | null;
            /** Min Sales */
            min_sales?: number | null;
            /** Season */
            season?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_edit_api_images__image_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_events_api_images__image_id__edit_events_get: {
        parameters: {
            query: {
                job_id: string;
            };
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ocr_image_api_images__image_id__ocr_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcrResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_kits_api_kits_get: {
        parameters: {
            query?: {
                recent?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KitListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kit_events_api_kits__kit_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_generate_api_kits__kit_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_spec_api_kits__kit_id__spec_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_metrics_api_metrics_weekly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyMetricsResponse"];
                };
            };
        };
    };
    get_onboarding_needed_api_onboarding_needed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingNeededResponse"];
                };
            };
        };
    };
    save_endpoints_api_providers_endpoints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveEndpointsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveEndpointsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_health_api_providers_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderHealthRow"][];
                };
            };
        };
    };
    get_provider_summary_api_providers_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersSummaryResponse"];
                };
            };
        };
    };
    get_active_queue_api_queue_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueJob"][];
                };
            };
        };
    };
    search_api_retrieval_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
